$(document).ready(function() {
   
var occupations =   [
{ value: 'Academic librarian' },
{ value: 'Accountant (certified)' },
{ value: 'Accountant (chartered)' },
{ value: 'Accountant (public finance, chartered)' },
{ value: 'Accountant (tax, chartered)' },
{ value: 'Accounting technician' },
{ value: 'Actuary' },
{ value: 'Adult nurse' },
{ value: 'Advertising account executive' },
{ value: 'Advertising account planner' },
{ value: 'Advertising copywriter' },
{ value: 'Advice worker' },
{ value: 'Advocate (Scotland)' },
{ value: 'Aeronautical engineer' },
{ value: 'Agricultural consultant' },
{ value: 'Agricultural manager' },
{ value: 'Aid worker/humanitarian worker' },
{ value: 'Air traffic controller' },
{ value: 'Airline cabin crew' },
{ value: 'Amenity horticulturist' },
{ value: 'Analytical chemist' },
{ value: 'Animal nutritionist' },
{ value: 'Animator' },
{ value: 'Applications programmer' },
{ value: 'Archaeologist' },
{ value: 'Architect' },
{ value: 'Architectural technologist' },
{ value: 'Archivist' },
{ value: 'Armed forces officer' },
{ value: 'Aromatherapist' },
{ value: 'Art therapist' },
{ value: 'Arts administrator' },
{ value: 'Auditor' },
{ value: 'Automotive engineer' },
{ value: 'Barrister\'s clerk' },
{ value: 'Barrister' },
{ value: 'Bilingual secretary' },
{ value: 'Biomedical engineer' },
{ value: 'Biomedical scientist' },
{ value: 'Broadcasting presenter' },
{ value: 'Building control officer/surveyor' },
{ value: 'Building services engineer' },
{ value: 'Building surveyor' },
{ value: 'Camera operator' },
{ value: 'Careers adviser (higher education)' },
{ value: 'Careers adviser' },
{ value: 'Careers consultant' },
{ value: 'Cartographer' },
{ value: 'Catering manager' },
{ value: 'Charities administrator' },
{ value: 'Charities fundraiser' },
{ value: 'Chemical (process) engineer' },
{ value: 'Child psychotherapist' },
{ value: 'Children\'s nurse' },
{ value: 'Chiropractor' },
{ value: 'Civil engineer' },
{ value: 'Civil Servant' },
{ value: 'Civil Service administrator' },
{ value: 'Clinical biochemist' },
{ value: 'Clinical cytogeneticist' },
{ value: 'Clinical microbiologist' },
{ value: 'Clinical molecular geneticist' },
{ value: 'Clinical research associate' },
{ value: 'Clinical scientist - tissue typing' },
{ value: 'Clothing and textile technologist' },
{ value: 'Colour technologist' },
{ value: 'Commercial horticulturist' },
{ value: 'Commissioning editor' },
{ value: 'Commissioning engineer' },
{ value: 'Commodity broker' },
{ value: 'Communications engineer' },
{ value: 'Community arts worker' },
{ value: 'Community education officer' },
{ value: 'Community worker' },
{ value: 'Company secretary' },
{ value: 'Computer sales support' },
{ value: 'Conference organiser' },
{ value: 'Construction manager' },
{ value: 'Consumer rights adviser' },
{ value: 'Control and instrumentation engineer' },
{ value: 'Corporate banker' },
{ value: 'Corporate treasurer' },
{ value: 'Counsellor' },
{ value: 'Courier/tour guide' },
{ value: 'Court reporter/verbatim reporter' },
{ value: 'Credit analyst' },
{ value: 'Crown Prosecution Service lawyer' },
{ value: 'Curator' },
{ value: 'Customs and excise officer' },
{ value: 'Customs officer' },
{ value: 'Dance movement therapist' },
{ value: 'Database administrator' },
{ value: 'Debt/finance adviser' },
{ value: 'Dental hygienist' },
{ value: 'Dentist' },
{ value: 'Dietitian' },
{ value: 'Diplomatic service' },
{ value: 'Doctor (general practitioner, GP)' },
{ value: 'Doctor (hospital)' },
{ value: 'Dramatherapist' },
{ value: 'Economist' },
{ value: 'Editorial assistant' },
{ value: 'Education administrator' },
{ value: 'Electrical engineer' },
{ value: 'Employment advice worker' },
{ value: 'Energy conservation officer' },
{ value: 'Engineering geologist' },
{ value: 'Environmental education officer' },
{ value: 'Environmental health officer' },
{ value: 'Environmental manager' },
{ value: 'Equal opportunities officer' },
{ value: 'Ergonomist' },
{ value: 'Estate agent' },
{ value: 'European Commission administrators' },
{ value: 'Exhibition display designer' },
{ value: 'Exhibition organiser' },
{ value: 'Exploration geologist' },
{ value: 'Facilities manager' },
{ value: 'Field trials officer' },
{ value: 'Financial manager' },
{ value: 'Firefighter' },
{ value: 'Fisheries officer' },
{ value: 'Fitness centre manager' },
{ value: 'Food scientist' },
{ value: 'Food technologist' },
{ value: 'Forensic scientist' },
{ value: 'Geographical information systems manager' },
{ value: 'Geomatics/land surveyor' },
{ value: 'Government lawyer' },
{ value: 'Government research officer' },
{ value: 'Graphic designer' },
{ value: 'Health and safety adviser' },
{ value: 'Health and safety inspector' },
{ value: 'Health promotion specialist' },
{ value: 'Health service manager' },
{ value: 'Health visitor' },
{ value: 'Herbalist' },
{ value: 'Heritage manager' },
{ value: 'Higher education administrator' },
{ value: 'Higher education advice worker' },
{ value: 'Homeless worker' },
{ value: 'Horticultural consultant' },
{ value: 'Hotel manager' },
{ value: 'Housing adviser' },
{ value: 'Hydrologist' },
{ value: 'Illustrator' },
{ value: 'Immigration officer' },
{ value: 'Immunologist' },
{ value: 'Industrial/product designer' },
{ value: 'Information scientist' },
{ value: 'Information systems manager' },
{ value: 'Information technology/software trainers' },
{ value: 'Insurance broker' },
{ value: 'Insurance claims inspector' },
{ value: 'Insurance risk surveyor' },
{ value: 'Insurance underwriter' },
{ value: 'Interpreter' },
{ value: 'Investment analyst' },
{ value: 'Investment banker - corporate finance' },
{ value: 'Investment banker – operations' },
{ value: 'Investment banker' },
{ value: 'Investment fund manager' },
{ value: 'IT consultant' },
{ value: 'IT technical support officer' },
{ value: 'Journalist' },
{ value: 'Land-based engineer' },
{ value: 'Landscape architect' },
{ value: 'Learning disability nurse' },
{ value: 'Learning mentor' },
{ value: 'Lecturer (adult education)' },
{ value: 'Lecturer (further education)' },
{ value: 'Lecturer (higher education)' },
{ value: 'Legal executive' },
{ value: 'Leisure centre manager' },
{ value: 'Licensed conveyancer' },
{ value: 'Local government administrator' },
{ value: 'Local government lawyer' },
{ value: 'Logistics/distribution manager' },
{ value: 'Loss adjuster (chartered)' },
{ value: 'Magazine features editor' },
{ value: 'Magazine journalist' },
{ value: 'Maintenance engineer' },
{ value: 'Management accountant' },
{ value: 'Management consultant (strategic)' },
{ value: 'Management consultant' },
{ value: 'Manufacturing engineer' },
{ value: 'Marine scientist' },
{ value: 'Market research executive' },
{ value: 'Marketing account manager' },
{ value: 'Marketing assistant' },
{ value: 'Marketing executive' },
{ value: 'Materials engineer' },
{ value: 'Materials specialist' },
{ value: 'Mechanical engineer' },
{ value: 'Media analyst' },
{ value: 'Media buyer' },
{ value: 'Media planner' },
{ value: 'Medical physicist' },
{ value: 'Medical representative' },
{ value: 'Mental health nurse' },
{ value: 'Metallurgist' },
{ value: 'Meteorologist' },
{ value: 'Microbiologist' },
{ value: 'Midwife' },
{ value: 'Mining engineer' },
{ value: 'Multimedia programmer' },
{ value: 'Multimedia specialists' },
{ value: 'Museum education officer' },
{ value: 'Museum/gallery exhibition officer' },
{ value: 'Music therapist' },
{ value: 'Nature conservation officer' },
{ value: 'Naval architect' },
{ value: 'Network administrator' },
{ value: 'Nurse' },
{ value: 'Nutritional therapist' },
{ value: 'Nutritionist' },
{ value: 'Occupational therapist' },
{ value: 'Oceanographer' },
{ value: 'Office manager' },
{ value: 'Operational researcher' },
{ value: 'Orthoptist' },
{ value: 'Outdoor pursuits manager' },
{ value: 'Packaging technologist' },
{ value: 'Paediatric nurse' },
{ value: 'Paramedic' },
{ value: 'Patent attorney' },
{ value: 'Patent examiner' },
{ value: 'Pension scheme manager' },
{ value: 'Personal assistant' },
{ value: 'Personnel officer' },
{ value: 'Petroleum engineer' },
{ value: 'Pharmacologist' },
{ value: 'Photographer' },
{ value: 'Physiotherapist' },
{ value: 'Picture researcher' },
{ value: 'Planning surveyor' },
{ value: 'Planning technician' },
{ value: 'Plant breeder' },
{ value: 'Police officer' },
{ value: 'Political party agent' },
{ value: 'Political party research officer' },
{ value: 'Practice nurse' },
{ value: 'Press photographer' },
{ value: 'Press sub-editor' },
{ value: 'Prison officer' },
{ value: 'Private music teacher' },
{ value: 'Probation officer' },
{ value: 'Product development scientist' },
{ value: 'Production manager' },
{ value: 'Programme researcher' },
{ value: 'Project manager' },
{ value: 'Psychologist (clinical)' },
{ value: 'Psychologist (educational)' },
{ value: 'Psychotherapist' },
{ value: 'Public affairs consultant (lobbyist)' },
{ value: 'Public affairs consultant (research)' },
{ value: 'Public house manager' },
{ value: 'Public librarian' },
{ value: 'Public relations (PR) officer' },
{ value: 'Quality assurance manager' },
{ value: 'Quantity surveyor' },
{ value: 'Race relations worker' },
{ value: 'Records manager' },
{ value: 'Recruitment consultant' },
{ value: 'Recycling officer' },
{ value: 'Regulatory affairs officer' },
{ value: 'Research scientist' },
{ value: 'Restaurant manager' },
{ value: 'Retail banker' },
{ value: 'Retail buyer' },
{ value: 'Retail manager' },
{ value: 'Retail merchandiser' },
{ value: 'Retail pharmacist' },
{ value: 'Sales executive' },
{ value: 'Scene of crime officer' },
{ value: 'Scientific laboratory technician' },
{ value: 'Secretary' },
{ value: 'Seismic interpreter' },
{ value: 'Site engineer' },
{ value: 'Site manager' },
{ value: 'Social researcher' },
{ value: 'Social worker' },
{ value: 'Software engineer' },
{ value: 'Soil scientist' },
{ value: 'Solicitor' },
{ value: 'Speech and language therapist' },
{ value: 'Sports coach' },
{ value: 'Sports development officer' },
{ value: 'Sports therapist' },
{ value: 'Statistician' },
{ value: 'Stockbroker' },
{ value: 'Structural engineer' },
{ value: 'Surveyor' },
{ value: 'Systems analyst' },
{ value: 'Systems designer/builder' },
{ value: 'Systems developer' },
{ value: 'Systems programmer' },
{ value: 'Tax adviser' },
{ value: 'Tax inspector' },
{ value: 'Teacher (nursery/pre-school)' },
{ value: 'Teacher (primary)' },
{ value: 'Teacher (secondary)' },
{ value: 'Teacher (special educational needs)' },
{ value: 'Teaching/classroom assistant' },
{ value: 'Technical author' },
{ value: 'Technical sales engineer' },
{ value: 'TEFL/TESL teacher' },
{ value: 'Television production assistant' },
{ value: 'Tour operator' },
{ value: 'Tour/holiday representative' },
{ value: 'Tourism officer' },
{ value: 'Tourist information manager' },
{ value: 'Town and country planner' },
{ value: 'Toxicologist' },
{ value: 'Trade union research officer' },
{ value: 'Trader' },
{ value: 'Trading standards officer' },
{ value: 'Training and development officer' },
{ value: 'Translator' },
{ value: 'Transportation planner' },
{ value: 'Travel agent' },
{ value: 'TV/film/theatre set designer' },
{ value: 'Urban general practice surveyor' },
{ value: 'Veterinary nurse' },
{ value: 'Veterinary surgeon' },
{ value: 'Volunteer work organiser' },
{ value: 'Warehouse manager' },
{ value: 'Waste disposal officer' },
{ value: 'Water conservation officer' },
{ value: 'Water engineer' },
{ value: 'Web designer' },
{ value: 'Welfare rights adviser' },
{ value: 'Writer' },
{ value: 'Youth worker' },

];
 
    
    // constructs the suggestion engine
var occupations = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  local: occupations
});
 
// kicks off the loading/processing of `local` and `prefetch`
occupations.initialize();

 var occupationstypeahead = $('#occupations.typeahead');
	occupationstypeahead.typeahead({
	  hint: true,
	  highlight: true,
	  minLength: 1
	},
	{
	  name: 'occupations',
	  displayKey: 'value',
	  // `ttAdapter` wraps the suggestion engine in an adapter that
	  // is compatible with the typeahead jQuery plugin
	  source: occupations.ttAdapter()
	});

var occupationsSelectedHandler = function (eventObject, suggestionObject, suggestionDataset) {
	//$("#next").prop("href", "amount.html");

};

occupationstypeahead.on('typeahead:selected', occupationsSelectedHandler );

$("#occupations").on("change", function(){
	$("#next").prop("href", defaultnext);

	if (occupationstypeahead.typeahead('val') == ""){
	   
	}
});



$("#btn-clear").on("click", function(){
		clearfilter();
		$("#occupations").focus();
});



function clearfilter(){
	occupationstypeahead.typeahead('val', '');
}

});