$(document).ready(function() {
   
var creditors =   [
{ type: 'local', address: '274 Lesborne Road, Reigate, Surrey, RH2 7JP', value: 'Goods Abundant Ltd' },
{ type: 'local', address: 'Walton House 56-58, Richmond Hill, Bournemouth, BH2 6EX', value: 'ABC Company' },

{ type: 'inss', address: 'The Omnibus Building, Lesborne Road, Reigate, Surrey, RH2 7JP', value: '1st  Credit' },
{ type: 'inss', address: 'c/o KPMG, FAO Lynn Taylor, National Client Service Centre, One Snowhill, Snow Hill Queensway, Birmingham, B4 6GH', value: 'Abbey National Plc' },
{ type: 'inss', address: 'c/o KPMG, FAO Lynn Taylor, National Client Service Centre, One Snowhill, Snow Hill Queensway, Birmingham, B4 6GH', value: 'Abbey National Plc' },
{ type: 'inss', address: 'Express House, Clayton Business Park, Petre Road, Accrington, Lancashire, BB5 5JY', value: 'Ace Cards and Gifts' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Additions Direct' },
{ type: 'inss', address: 'Minton Hollins Building, Shelton Old Road, Stoke-on-Trent, ST4 7RY', value: 'Advantis Credit' },
{ type: 'inss', address: 'Debt Collection Department, Bishops Rise, Hatfield, Herts, AL10 9HL', value: 'Affinity Water' },
{ type: 'inss', address: 'PO Box 444, Bromley, BR1 1ZB', value: 'Aktiv Kapital' },
{ type: 'inss', address: 'Essex & Suffolk Water Customer Care, FAO Warren Pitts, PO Box 292, Durhan, DH1 9TX', value: 'Alexander James & Co Ltd' },
{ type: 'inss', address: 'c/o KPMG, FAO Lynn Taylor, National Client Service Centre, One Snowhill, Snow Hill Queensway, Birmingham, B4 6GH', value: 'Alliance & Leicester Plc' },
{ type: 'inss', address: 'c/o KPMG, FAO Lynn Taylor, National Client Service Centre, One Snowhill, Snow Hill Queensway, Birmingham, B4 6GH', value: 'Alliance & Leicester Plc' },
{ type: 'inss', address: 'Registered Office: Adamson House, Towers Business Park, Didsbury, Manchester, M20 2YY.', value: 'Allied International Credit (UK) Ltd' },
{ type: 'inss', address: 'FAO Graham Wallis, American Express Insolvencies, PO Box 1028, Maidstone, Kent, ME19 8WW', value: 'American Express' },
{ type: 'inss', address: 'Walton House 56-58, Richmond Hill, Bournemouth, BH2 6EX', value: 'Amigo Loans' },
{ type: 'inss', address: 'Customer Services, PO Box 10642, Harlow, Essex, CM20 9HA', value: 'Anglian Water Services Ltd' },
{ type: 'inss', address: 'Apex House, 27 Arden Street, Stratford-Upon-Avon, Warwickshire, CV37 6NW', value: 'Apex Credit Management' },
{ type: 'inss', address: 'First Data, Janus House, JPT/G, Endeavour Drive, Basildon, Essex, SS14 3WF', value: 'Aqua' },
{ type: 'inss', address: 'Kent House, Churchfield Road, Walton on Thames, Surrey, KT12 2TU', value: 'ARC (Europe) Ltd' },
{ type: 'inss', address: 'Home Retail Group (Admin Dept.), Unit 1-12 Futura Park, Aspinall Way, Horwich, Bolton, Lancashire, BL6 6PG', value: 'Argos' },
{ type: 'inss', address: 'Barclaycard, Specialist Support Unit, PO Box 5402, Northampton, Northamptonshire, NN4 1ZR', value: 'Argos Mastercard' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Arrears Collection Department (Shop Direct)' },
{ type: 'inss', address: '3rd Floor, 15 Old Bailey, London, EC4M 7EF', value: 'Arrow Global LLC' },
{ type: 'inss', address: '2-3 Triton Square, Regents Place, London, NW1 3AN', value: 'ASDA Card Services' },
{ type: 'inss', address: 'Civic Centre, Tannery Lane, Ashford, Kent, TN23 1PL', value: 'Ashford Borough Council' },
{ type: 'inss', address: 'PO Box 30095, London, SE1 7WU', value: 'Asset Link Capital (No. 1) Limited' },
{ type: 'inss', address: '3 Earlstrees Road, Earlstrees Industrial Estate, Corby, Northamptonshire, NN17 4AZ', value: 'Avon' },
{ type: 'inss', address: 'Credit Recovery, 4th Floor, Bow Bells House, 1 Bread Street, London, EC4M 9BE', value: 'Bank Of Ireland GB Ltd' },
{ type: 'inss', address: 'Credit Recovery, 4th Floor, Bow Bells House, 1 Bread Street, London, EC4M 9BE', value: 'Bank Of Ireland GB Ltd' },
{ type: 'inss', address: 'Personal Insolvencies, Dundas House, PO Box 66, Rosyth, Fife, KY11 2YG', value: 'Bank of Scotland' },
{ type: 'inss', address: 'Personal Insolvencies, Dundas House, PO Box 66, Rosyth, Fife, KY11 2YG', value: 'Bank of Scotland' },
{ type: 'inss', address: 'Specialist Support Unit, Collections Floor 6, PO Box 5402, Northampton, NN4 1ZR', value: 'Barclaycard' },
{ type: 'inss', address: 'Open Sort & Distribute, Astron House, 51 Saffron Road, Leicester, LE87 2BB', value: 'Barclays Bank Plc' },
{ type: 'inss', address: 'c/o Grant Thornton UK LLP, Hartwell House, 55-61 Victoria Street, Bristol, Avon, BS1 6FT', value: 'Barclays Partner Finance' },
{ type: 'inss', address: '24 George Square, Glasgow, Lanarkshire, G2 1EG', value: 'BCW Group Plc' },
{ type: 'inss', address: 'A015, Town Hall, St Pauls Square, Bedford, MK40 1SJ', value: 'Bedford Borough Council' },
{ type: 'inss', address: 'Insolvency Team, PO Box 5206, Coventry, West Midlands, CV3 9FA', value: 'Beneficial Finance' },
{ type: 'inss', address: 'Barclaycard, Specialist Support Unit, PO Box 5402, Northampton, Northamptonshire, NN4 1ZR', value: 'BHS' },
{ type: 'inss', address: 'Rossendale Borough Council, Admail ADM 4005, Rossendale, BB4 4ZR.', value: 'Blackburn with Darwen Council' },
{ type: 'inss', address: 'Collections, St. William House, Tresillian Terrace, Cardiff, CF10 5BH', value: 'Blackhorse' },
{ type: 'inss', address: 'Revenue Section, Town Hall, Blackpool, Lancashire, FY1 1NF', value: 'Blackpool Council' },
{ type: 'inss', address: 'Personal Insolvencies, Dundas House, PO Box 66, Rosyth, Fife, KY11 2YG', value: 'Blair Oliver & Scott Ltd' },
{ type: 'inss', address: 'Le Mans Crescent, Bolton, Lancashire, BL1 1SA', value: 'Bolton Borough Council' },
{ type: 'inss', address: 'George Jessel House, Francis Avenue, Bournemouth, Dorset, BH11 8NX', value: 'Bournemouth & West Hampshire Water Plc' },
{ type: 'inss', address: 'Court Team,Council Tax Dept., Britannia House, Hall Ings, Bradford, BD1 1HX', value: 'Bradford District Council' },
{ type: 'inss', address: 'Causeway House, Braintree, Essex, CM7 9HB', value: 'Braintree District Council' },
{ type: 'inss', address: 'Anglia Revenues Partnership, Breckland House, St Nicholas Street, Thetford, Norfolk, IP24 1BT', value: 'Breckland District Council' },
{ type: 'inss', address: 'The Council House, College Green, Avon, BS1 5TR', value: 'Bristol City Council' },
{ type: 'inss', address: '1 Clevedon Walk, Nailsea, Bristol, Avon, BS48 1WA', value: 'Bristol Water' },
{ type: 'inss', address: 'Bristow & Sutor, Bartleet Road, Washfrod, Redditch, B98 0FL', value: 'Bristow & Sutor' },
{ type: 'inss', address: 'EDC Bankruptcy Team (EXL), PO Box 59, Hyde, Cheshire, SK14 3QU', value: 'British Gas Trading Ltd' },
{ type: 'inss', address: 'DM Team, PP CPC3D, Charnwood Place, 1 South Albion Street, Leicester, Leicestershire, LE1 6JL', value: 'British Telecom plc' },
{ type: 'inss', address: 'Debt Relief Orders, Collections, Brunswick Point, Wade Lane, PO Box 764, Leeds, West Yorkshire, LS1 9JJ', value: 'Brunswick Collections Ltd' },
{ type: 'inss', address: 'De Havilland Drive, Brooklands Business Park, Weybridge, Surrey, KT13 0NT', value: 'Bryan Carter & Co Solicitors' },
{ type: 'inss', address: '24 George Square, Glasgow, Lanarkshire, G2 1EG', value: 'Buchanan Clark & Wells' },
{ type: 'inss', address: '3 Godwin Street, Bradford, West Yorkshire, BD1 2SA', value: 'C K Edrupt & Co' },
{ type: 'inss', address: 'Viewpoint, Basing View, Basingstoke, Hampshire, RG21 4RG', value: 'C.A.R.S' },
{ type: 'inss', address: '1 Kings Hill Avenue, Kings Hill, West Malling, Kent, ME19 4UA', value: 'Cabot Financial (UK) Ltd' },
{ type: 'inss', address: 'c/o KPMG, FAO Lynn Taylor, National Client Service Centre, One Snowhill, Snowhill, Queensway, Birmingham, B4 6GH', value: 'Cahoot' },
{ type: 'inss', address: 'Town Hall, Halifax, West Yorkshire, HX1 1UJ', value: 'Calderdale Borough Council' },
{ type: 'inss', address: '90 Fulbourn Road, Cambridge, Cambridgeshire, CB1 9NJ', value: 'Cambridge Water Plc' },
{ type: 'inss', address: 'Specialist Support Unit, Capital One Services, PO Box 5282, Nottingham, Nottinghamshire, NG2 3YH', value: 'Capital One Bank Europe Plc' },
{ type: 'inss', address: 'Specialist Support Unit, Capital One Services, PO Box 5282, Nottingham, Nottinghamshire, NG2 3YH', value: 'Capital One Bank Europe Plc' },
{ type: 'inss', address: '27 Rye Close, Hampshire, GU51 2QQ', value: 'CapQuest Debt Recovery Ltd' },
{ type: 'inss', address: 'County Hall, Atlantic Warf, Cardiff, South Glamorgan, CF10 4UW', value: 'Cardiff City Council' },
{ type: 'inss', address: 'Collections Department, Lambourne House, Lambourne Crescent, Cardiff Business Park, Llanishen, Cardiff, CF14 5GL', value: 'Carlyle Finance Ltd' },
{ type: 'inss', address: '1 Portal Way, London, W3 6RS', value: 'Carphone Warehouse' },
{ type: 'inss', address: 'Suite 701, Lowry House, 17 Marble Street, Manchester, M23AW', value: 'Cash Choice UK ' },
{ type: 'inss', address: 'Innovation House, Aston Lane South, Preston Brook, Cheshire, WA7 3BW', value: 'Cash Converters' },
{ type: 'inss', address: '2 Reavell Place, Ipswich, IP2 0ET', value: 'Cash Genie' },
{ type: 'inss', address: '797 London Road, Thornton, Croydon, Surrey, CR7 6YY', value: 'CCS Collect' },
{ type: 'inss', address: '2nd Floor, 12 Calthorpe Road, Edgbaston, Birmingham, West Midlands, B15 1FD', value: 'Central Debt Recovery Unit (HSBC)' },
{ type: 'inss', address: '2nd Floor, Burgage Square, Merchant Gate, Wakefield, WF1 2TS', value: 'Chantry Collections' },
{ type: 'inss', address: 'Council Tax, Southfields, Loughborough, LE11 2TU', value: 'Charnwood Borough Council' },
{ type: 'inss', address: 'PO Box 39, Town Hall, Macclesfield, Cheshire, SK10 1HR', value: 'Cheshire East Council' },
{ type: 'inss', address: 'PO Box 187, ELLESMERE PORT, CH34 9DB', value: 'Cheshire West and Chester Council' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Choice' },
{ type: 'inss', address: '2nd floor, The Wharf, Neville Street, Leeds, LS1 4AZ', value: 'Churchill Insurance Co Ltd' },
{ type: 'inss', address: 'c/o Grant Thornton UK LLP, Hartwell House, 55-61 Victoria Street, Bristol, Avon, BS1 6FT', value: 'Citibank International Plc' },
{ type: 'inss', address: 'c/o Grant Thornton UK LLP, Hartwell House, 55-61 Victoria Street, Bristol, Avon, BS1 6FT', value: 'Citibank International Plc' },
{ type: 'inss', address: 'Pelham Street, Brighton, BN1 4FA', value: 'City College Brighton & Hove' },
{ type: 'inss', address: 'Lawrence House, Riverside Drive, Cleckheaton, West Yorkshire, BD19 4DH', value: 'CL Finance' },
{ type: 'inss', address: 'PO Box 336, Lamport, Northampton, Northamptionshire, NN6 9WZ', value: 'Clarity Credit Management Solutions' },
{ type: 'inss', address: 'CLC Finance, Unit 4, Meadow court, Millshaw, Leeds, LS11 8LZ', value: 'CLC Finance' },
{ type: 'inss', address: 'Debt Relief Orders, Collections, Brunswick Point, Wqade Lane, PO Box 764, Leeds, West Yorkshire, LS1 9JJ', value: 'Clydesdale Bank Plc' },
{ type: 'inss', address: 'Debt Relief Orders, Collections, Brunswick Point, Wqade Lane, PO Box 764, Leeds, West Yorkshire, LS1 9JJ', value: 'Clydesdale Bank Plc' },
{ type: 'inss', address: 'Income Management, Rowan House, Sheepen Road, Colchester, CO3 3WG', value: 'Colchester Borough Council' },
{ type: 'inss', address: 'Bellway House, 7 Worcester Road, Bromsgrove, B61 7DL', value: 'Commercial Credit Services' },
{ type: 'inss', address: 'Compass House, Waterside, Hanbury Road, Bromsgrove, B60 4FD', value: 'Controlaccount' },
{ type: 'inss', address: 'c/o Grant Thornton UK LLP, Hartwell House, 55-61 Victoria Street, Bristol, Avon, BS1 6FT', value: 'Co-operative Bank Plc' },
{ type: 'inss', address: 'c/o Grant Thornton UK LLP, Hartwell House, 55-61 Victoria Street, Bristol, Avon, BS1 6FT', value: 'Co-operative Bank Plc' },
{ type: 'inss', address: 'The Copeland Centre, Catherine Street, Whitehaven, Cumbria, CA28 7SJ', value: 'Copeland Borough Council (Housing Benefit Overpayments)' },
{ type: 'inss', address: 'PO Box 676, Threemilestone Truro, TR4 9LD', value: 'Cornwall Council' },
{ type: 'inss', address: 'DCA Team, Chadwick House, Blenheim Court, Solihull, West Midlands, B91 2AA', value: 'Creation Finance Service' },
{ type: 'inss', address: 'PO Box 650, Weybridge, Surrey, KT13 3EN', value: 'Credit Account Management Ltd' },
{ type: 'inss', address: 'The Old Court House, 70-72 High Street, Aylesbury, Buckinghamshire, HP22 4JS', value: 'Credit Security Ltd' },
{ type: 'inss', address: 'Capella Court, 725 Brighton Road, Purley, Surrey, CR8 2PG', value: 'Credit Solutions Ltd' },
{ type: 'inss', address: '96 Wharf Street, Dukinfield, Cheshire, SK16 4RA', value: 'Cygnet Financial Service Ltd' },
{ type: 'inss', address: 'Revenues Division, Civic Centre, Marlowes, Hemel Hempstead, HP1 1HH', value: 'Dacorum Borough Council' },
{ type: 'inss', address: 'Early Charge Off Department, Capital House, 1 Bruntcliffe Way, Morley, West Yorkshire, LS27 0JG', value: 'Debenhams' },
{ type: 'inss', address: 'Department 5, PO Box 13, Acctington, Lancashire, BB5 5GR', value: 'Debt Collection & Security' },
{ type: 'inss', address: 'The Heriot Building, Dodds Close, Rotherham, S60 1BX', value: 'Debt Managers Ltd' },
{ type: 'inss', address: 'Packsaddle, Wrexham Road, Rhosyllen, Wrexham, LL14 4EH', value: 'Dee Valley Water' },
{ type: 'inss', address: 'Buckingham Road, Brackley, Northamptonshire, NN13 7DN', value: 'Direct Legal & Collections' },
{ type: 'inss', address: 'c/o RSM Tenon, FAO Robert Beat, Salisbury House, 31 Finsbury Circus, London, EC2M 5SQ', value: 'Direct Line' },
{ type: 'inss', address: '2nd floor, The Wharf, Neville Street, Leeds, LS1 4AZ', value: 'Direct Line Insurance Plc' },
{ type: 'inss', address: 'Droyds Debt & Collection Services, Bradford, West Yorkshire, BD1 1DA', value: 'Droyds Debt & Collection Services' },
{ type: 'inss', address: 'Revenue Services, PO Box 3, Council House, Priory Street, Dudley, West Midlands, DY1 1HG', value: 'Dudley Metropolitan Borough Council - Council Tax' },
{ type: 'inss', address: 'Debt Management (SF), PO Box 171, Mitcheldean, Gloucestershire, GL17 0XH', value: 'DWP (Benefit Overpayments)' },
{ type: 'inss', address: 'Debt Management (SF), PO Box 171, Mitcheldean, Gloucestershire, GL17 0XH', value: 'DWP (Social Fund) Excluded Debt' },
{ type: 'inss', address: 'Veolia Water Outsourcing Ltd, Dwr Cymru Customer Services, Linea, Fortran Road, St. Mellons, Cardiff, CF3 0LT', value: 'Dwr Cymru - Welsh Water Ltd' },
{ type: 'inss', address: 'Insolvency Department, Newland House, 49 Mount Street, NOTTINGHAM, NG1 6PG', value: 'E.ON UK Plc' },
{ type: 'inss', address: 'Anglia Revenues Partnership, Breckland House, St Nicholas Street, Thetford, Norfolk, IP24 1BT', value: 'East Cambridgeshire District Council' },
{ type: 'inss', address: 'Freepost RRYZ-BGYG-JCXR, EDF Energy, 334 Outland Road, Plymouth, PL3 5TU', value: 'EDF Energy Ltd' },
{ type: 'inss', address: 'c/o Grant Thornton UK LLP, Hartwell House, 55-61 Victoria Street, Bristol, Avon, BS1 6FT', value: 'Egg Banking Plc' },
{ type: 'inss', address: 'c/o Grant Thornton UK LLP, Hartwell House, 55-61 Victoria Street, Bristol, Avon, BS1 6FT', value: 'Egg Banking Plc' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Empire Stores' },
{ type: 'inss', address: '2 Birchwood Office Park, Crab Lane, Fearnhead, Warrington, Cheshire, WA2 0XS', value: 'EOS Solutions UK Plc' },
{ type: 'inss', address: '323 High Street, Epping, Essex, CM16 4BZ', value: 'Epping Forest District Council' },
{ type: 'inss', address: 'Equity House, Ettington Road, Wellesbourne, Warwick, Warwickshire, CV35 9GA', value: 'Equidebt' },
{ type: 'inss', address: 'Essex & Suffolk Water, Bankruptcy & Liquidation Team, P O Box 292, Durham, DH1 9TX', value: 'Essex & Suffolk Water Ltd' },
{ type: 'inss', address: 'Fairfax House, Merrion Street, Leeds, West Yorkshire, LS2 8HE', value: 'Eversheds Solicitors' },
{ type: 'inss', address: 'Council Tax Recovery, Room 1.7, Civic Centre, EX1 1JN', value: 'Exeter City Council' },
{ type: 'inss', address: 'Experto Credite Ltd, Inspired, Easthampstead Road, Bracknell, RG12 1NS', value: 'Experto Credite Ltd' },
{ type: 'inss', address: 'Debt Relief Orders, Collections, PO Box 764. Bruswick Point, Wade Lane, Leeds, LS11 9JJ', value: 'Fairhalsen Collections Ltd' },
{ type: 'inss', address: 'Griffin House, 40 Lever Street, Manchester, M60 6ES', value: 'Fashion World' },
{ type: 'inss', address: '5th Floor, Maitland House, Warrior Square, Southend-On-Sea, Essex, SS1 2JS', value: 'Fenton Cooper' },
{ type: 'inss', address: 'Repayment Services S/CRS/RST, 40 Wakefield Road, Leeds, LS98 1FD', value: 'First Direct' },
{ type: 'inss', address: 'Repayment Services S/CRS/RST, 40 Wakefield Road, Leeds, LS98 1FD', value: 'First Direct' },
{ type: 'inss', address: 'Emerald House, Meadowcroft Way, Leigh, WN7 3XZ', value: 'First Response Finance Limited' },
{ type: 'inss', address: 'Walton House 56-58, Richmond Hill, Bournemouth, BH2 6EX', value: 'FLM Quick' },
{ type: 'inss', address: 'The Cherry Garden, Cherry Garden Lane, Folkstone, Kent, CT19 4QB', value: 'Folkestone & Dover Water Services Ltd' },
{ type: 'inss', address: 'Anglia Revenues Partnership, Breckland House, St Nicholas Street, Thetford, Norfolk, IP24 1BT', value: 'Forest Heath District Council' },
{ type: 'inss', address: 'Forest of Dean District Council, Council Offices, High Street, Coleford, Glos, GL16 8HG', value: 'Forest of Dean District Council' },
{ type: 'inss', address: 'Persimmon House, De Havilland Drive, Brooklands Business Park, Weybridge, Surrey, KT13 0NT', value: 'Fredrickson International Ltd' },
{ type: 'inss', address: '1 Amberley Street, Sheffield, South Yorkshire, S9 2FS', value: 'Freemans Plc' },
{ type: 'inss', address: 'Revenues Dept, Town Hall, South Promenade, Lytham St Annes, FY8 1LW', value: 'Fylde Borough Council' },
{ type: 'inss', address: 'Auto Recoveries, Capital House, 1 Bruntcliffe Way, Leeds, LS27 0JG', value: 'GE Money Auto' },
{ type: 'inss', address: 'Early Charge Off Department, Capital House, 1 Bruntcliffe Way, Morley, West Yorkshire, LS27 0JG', value: 'GE Money Ltd' },
{ type: 'inss', address: 'Early Charge Off Department, Capital House, 1 Bruntcliffe Way, Morley, West Yorkshire, LS27 0JG', value: 'GE Money Ltd' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'General Credit Company (Shop Direct)' },
{ type: 'inss', address: 'Warwick House, Birmingham Road, Stratford-Upon-Avon, Warwickshire, CV37 0BP', value: 'Geoffrey Parker Bourne Solicitors' },
{ type: 'inss', address: '66/70 Coombe Road, New Malden, KT3 4QW', value: 'Global Debt Recovery' },
{ type: 'inss', address: 'Revenue Services, Herbert Warehouse, The Dock, Gloucester, GL1 2EQ', value: 'Gloucester City Council' },
{ type: 'inss', address: 'BCW Group (Gothia) Ltd, Groundfloor, Ridgeworth House, 5-9 Liverpool Gardens, Worthing, West Sussex, BN11 1RS', value: 'Gothia Ltd' },
{ type: 'inss', address: '1 Amberley Street, Sheffield, South Yorkshire, S9 2FS', value: 'Grattan Plc' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Great Universal Stores' },
{ type: 'inss', address: '1 Godwin Street, Bradford, BD1 2SU', value: 'Greenwood Personal Credit' },
{ type: 'inss', address: 'Personal Insolvencies, Dundas House, PO Box 66, Rosyth, Fife, KY11 2YG', value: 'Halifax' },
{ type: 'inss', address: 'Personal Insolvencies, Dundas House, PO Box 66, Rosyth, Fife, KY11 2YG', value: 'Halifax' },
{ type: 'inss', address: 'Enterprise House, 1 Apex View, Leeds, LS11 9BH', value: 'Hamptons Legal Services' },
{ type: 'inss', address: 'Insolvency Department, Gibson House, Huntingdon, Cambridgeshire, PE29 6WQ', value: 'Hartlepool Water' },
{ type: 'inss', address: 'Insolvency Team, PO Box 5206, Coventry, West Midlands, CV3 9FA', value: 'HFC Bank' },
{ type: 'inss', address: 'HBEU Collections, 1st Floor, 120 Edmund Street, Birmingham, B3 2QZ', value: 'HFC Bank' },
{ type: 'inss', address: 'c/o Turnbull Rutherford Solicitors, 165 The Broadway, London, SW19 1NE', value: 'HFO Services Ltd' },
{ type: 'inss', address: 'Buckingham Road, Brackley, NN13 7DN ', value: 'Hillesden Securities Limited' },
{ type: 'inss', address: 'Barclaycard, Specialist Support Unit, PO Box 5402, Northampton, Northamptonshire, NN4 1ZR', value: 'Hilton' },
{ type: 'inss', address: 'FAO John Lloyd, Debt Management & Banking, Regian House,James Street, Liverpool, Merseyside, L75 1AD', value: 'HM Revenue & Customs' },
{ type: 'inss', address: 'Home Retail Group (Admin Dept.), Unit 1-12 Futura Park, Aspinall Way, Horwich, Bolton, Lancashire, BL6 6PG', value: 'Homebase' },
{ type: 'inss', address: 'Axis Teo, Axis Park, Hurricane Way, Langley, SL3 8AG', value: 'Honda Finance Europe Plc' },
{ type: 'inss', address: 'Early Charge Off Department, Capital House, 1 Bruntcliffe Way, Leeds, LS27 0JG', value: 'House Of Fraser' },
{ type: 'inss', address: 'PO Box 110, Cleckheaton, West Yorkshire, BD19 4XT', value: 'Howard Cohen and Co' },
{ type: 'inss', address: 'Collections and Recoveries, 2nd Floor, 12 Calthorpe Road, Edgebaston, Birmingham, B15 1FD', value: 'HSBC' },
{ type: 'inss', address: 'Collections and Recoveries, 2nd Floor, 12 Calthorpe Road, Edgebaston, Birmingham, B15 1FD', value: 'HSBC' },
{ type: 'inss', address: 'Council Tax Section, First Floor, Treasury Building, Guildhall Road, Hull, HU1 2AB', value: 'Hull City Council' },
{ type: 'inss', address: 'PO Box 333, Glasgow, G2 9AG', value: 'Hutchison 3G UK Ltd' },
{ type: 'inss', address: 'Waterfront House, Waterfront Plaza, Station Street, Nottingham, NG2 3DQ', value: 'Ikano Financial Services Ltd' },
{ type: 'inss', address: 'Incommunities Income Team,  City House,  Cheapside,  Bradford  BD1 4HR', value: 'Incommunities' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Index Extra' },
{ type: 'inss', address: 'Credit Control, PO Box 17316, Edinburgh, EH12 1AY', value: 'Intelligent Finance' },
{ type: 'inss', address: 'Personal Insolvencies, Dundas House, PO Box 66, Rosyth, Fife, KY11 2YG', value: 'Intelligent Finance' },
{ type: 'inss', address: 'PO Box 7183, Harlow, Essex, CM19 5WE', value: 'Intrum Justitia Ltd' },
{ type: 'inss', address: 'Legal & Trade House, 33-34 Winckley Square, Preston, PR1 3JJ', value: 'iQOR Recovery Services' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Janet Fraser' },
{ type: 'inss', address: 'Credit Operations, MEN Arena, 23 Hunts Bank, Manchester, M3 1AX', value: 'JD Williams & Co Ltd' },
{ type: 'inss', address: 'Debt Relief Orders, Collections, PO Box 764, Bruswick Point, Wade Lane, Leeds, LS11 9JJ', value: 'Jeremy Sutcliffe & Co' },
{ type: 'inss', address: 'HBEU Collections, 1st Floor, 120 Edmund Street, Birmingham, B3 2QZ', value: 'John Lewis Partnership Card' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'John Moores' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Kays' },
{ type: 'inss', address: '132 Broad Street, Parkgate, Rotherham, S62 6ES', value: 'KDS Finance' },
{ type: 'inss', address: 'Kettering Borough Council, Municipal Offices, Bowling Green Road, Kettering, Northants, NN15 7BR', value: 'Kettering Borough Council' },
{ type: 'inss', address: 'Civic Centre 1 High Street HUDDERSFIELD, HD1 2NF', value: 'Kirklees Council' },
{ type: 'inss', address: 'Empire Buildings, Horbury Road, Wakefieldm WF90 8AA', value: 'La Redoute' },
{ type: 'inss', address: 'Legal Services Town Hall, Dalton Square, Lancaster, LA1 1PJ', value: 'Lancaster City Council' },
{ type: 'inss', address: 'Civic Hall, Calverley Street, Leeds, LS1 1UR', value: 'Leeds City Council' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Legal Direct Recoveries (Shop Direct)' },
{ type: 'inss', address: 'Wellington House, 22-32 Wellington Street, LEICESTER, LE1 6HL', value: 'Leicester City Council ' },
{ type: 'inss', address: 'Lawrence House, Riverside Drive, Cleckheaton, West Yorkshire, BD19 4DH', value: 'Lewis Debt Recovery' },
{ type: 'inss', address: 'PO Box 30095, London, SE1 7WU', value: 'Link Financial' },
{ type: 'inss', address: 'PO Box 30095, London, SE1 7WU', value: 'Link Financial Outsourcing Limited' },
{ type: 'inss', address: 'Crusader House 2nd Floor, 145-157 St. John Street, London, EC1V 4PY ', value: 'Liquid Advance' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Littlewoods' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Littlewoods Debt Collection' },
{ type: 'inss', address: 'PO Box 834, Liverpool, L69 2UT', value: 'Liverpool Direct Ltd' },
{ type: 'inss', address: 'Insolvency Team, 2nd Floor, 3 City Park, The Droveway, Hove, BN3 7AU', value: 'Lloyds Bank Plc' },
{ type: 'inss', address: 'Insolvency Team, 2nd Floor, 3 City Park, The Droveway, Hove, BN3 7AY', value: 'Lloyds Bank Plc' },
{ type: 'inss', address: '49 Huntbach Street, Hanley, Stoke-On-Trent, ST1 2BS', value: 'Loans at Home 4U' },
{ type: 'inss', address: 'c/o RSM Tenon, FAO Robert Beat, Salisbury House, 31 Finsbury Circus, London, EC2M 5SQ', value: 'Lombard' },
{ type: 'inss', address: 'Collections, St Catherines Court, Herbert Road, Solihull, B91 3QE', value: 'Lombard Direct' },
{ type: 'inss', address: 'Churchgate House, 56 Oxford Road, Manchester M1 6EU', value: 'London Scottish Bank Ltd' },
{ type: 'inss', address: 'PO Box 164, Leeds, LS10 9EH', value: 'Lowell Group' },
{ type: 'inss', address: 'Town Hall, George Street, Luton, Bedfordshire, LU1 2BQ', value: 'Luton Borough Council' },
{ type: 'inss', address: 'Kings Meadow, Chester Business Park, Cheshire, CH99 9FB', value: 'M&S Money' },
{ type: 'inss', address: 'Kings Meadow, Chester Business Park, Cheshire, CH99 9FB', value: 'M&S Money' },
{ type: 'inss', address: 'Unit 1A, 58 Portland Street, Kilmarnock, Ayrshire, KA1 1JG', value: 'Mackenzie Hall Ltd' },
{ type: 'inss', address: 'Princes Road, Maldon, CM9 5DL', value: 'Maldon District Council' },
{ type: 'inss', address: 'Revenues & Benefits Unit,Manchester City Council,PO Box 147,M15 5TU', value: 'Manchester City Council' },
{ type: 'inss', address: 'Personal Insolvencies, Dundas House, PO Box 66, Rosyth, Fife, KY11 2YG', value: 'Marbles' },
{ type: 'inss', address: 'First Data, Janus House, JPT/G, Endeavour Drive, Basildon, Essex, SS14 3WF', value: 'Marbles' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Marshall Ward' },
{ type: 'inss', address: 'Insolvency, PO Box 6302, Bournemouth, Dorset, BH1 9DY', value: 'Max Recovery Ltd' },
{ type: 'inss', address: 'MBNA Customer Assistance PO Box 30, Chester Business Park, Wrexham Road, Chester, Cheshire, CH4 9FD', value: 'MBNA Europe Bank Ltd' },
{ type: 'inss', address: 'PO Box 55, Kirkby, Liverpool, Merseyside, L32 8XX', value: 'Mercers Debt Collection' },
{ type: 'inss', address: 'Unit 2B, 58 Portland Street, Kilmarnock, Ayrshire, KA1 1JG', value: 'Meritforce' },
{ type: 'inss', address: 'Collections & Recoveries, 2nd Floor, 12 Calthorpe Road, Edgbaston, Birmingham, B15 1FD', value: 'Metropolital Collection Services Ltd (HSBC)' },
{ type: 'inss', address: 'Moorcroft House, 2 Spring Gardens, Stockport, Greater Manchester, SK1 4AN', value: 'Midas Legal Services' },
{ type: 'inss', address: 'c/o RSM Tenon, FAO Robert Beat, Salisbury House, 31 Finsbury Circus, London, EC2M 5SQ', value: 'Mint' },
{ type: 'inss', address: 'Birmingham Collections Centre, CVC Team, PO Box 5433, Birmingham, B1 2WZ', value: 'Mint Loans' },
{ type: 'inss', address: 'Fleming House, Seebeck Place, Knowlhill, Milton Keynes, MK5 8FR', value: 'MKDP LLP' },
{ type: 'inss', address: 'PO Box 6476, Northampton, Northamptonshire, NN4 1ZN', value: 'Monument Credit Card' },
{ type: 'inss', address: 'PO Box 17, 2 Spring Gardens, Stockport, Greater Manchester, SK1 4AJ', value: 'Moorcroft Debt Recovery' },
{ type: 'inss', address: 'Unit 2, Ball Mill Top, Main Road, Hallow, Worcester, Worcestershire, WR2 6LS', value: 'Morses Club' },
{ type: 'inss', address: '39 Bedford Street South, Leicester, Leicestershire, LE1 3JN', value: 'Mutual Clothing & Supply' },
{ type: 'inss', address: 'Lending Control (Insolvency), Kings Park Road, Moulton Park Industrial Estate, Northampton, Northamptonshire, NN3 6NW', value: 'Nationwide Building Society' },
{ type: 'inss', address: 'Lending Control (Insolvency), Kings Park Road, Moulton Park Industrial Estate, Northampton, Northamptonshire, NN3 6NW', value: 'Nationwide Building Society' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Nationwide Debt Recovery (Shop Direct)' },
{ type: 'inss', address: 'c/o RSM Tenon, FAO Robert Beat, Salisbury House, 31 Finsbury Circus, London, EC2M 5SQ', value: 'Natwest Plc' },
{ type: 'inss', address: 'Credit Management Services, PO Box 16337, 7 Brindley Place, Birmingham, B2 2YH', value: 'Natwest Plc' },
{ type: 'inss', address: '80 High Street, Sidcup, Kent, DA14 6DS', value: 'Nelson Guest' },
{ type: 'inss', address: 'Revenues and Benefits, Newcastle City Council, Civic Centre, Barrass Bridge, Newcastle upon Tyne, NE1 8QH', value: 'Newcastle City Council' },
{ type: 'inss', address: 'Revenues & Benefits, Newcastle City Council, Civic Centre, Room 201, Newcastle upon Tyne, NE1 8QH', value: 'Newcastle City Council (Housing Benefit Debt Recovery)' },
{ type: 'inss', address: 'Housing Department. Civic Centre, Newcastle Upon tyne, Tyne & Wear, NE1 8PR', value: 'Newcastle City Council (Housing Dept.)' },
{ type: 'inss', address: 'PO Box 4000, Leeds, LS2 8RZ', value: 'Next ' },
{ type: 'inss', address: 'Desford Road, Enderby, Leicester, LE19 4AT', value: 'Next Retail and Next Directory' },
{ type: 'inss', address: 'North Kesteven District Council, Revenues and Benefits Shared Service, PO Box 1257, Lincoln, LN5 5PQ', value: 'North Kesteven District Council' },
{ type: 'inss', address: 'Finance & Resources, Revenues & Benefits, North Somerset Council, PO Box 76, Town Hall, Weston-super-Mare, BS23 1YY', value: 'North Somerset Council' },
{ type: 'inss', address: 'North Tyneside Council, Recovery & Enforcement, Quadrant, PO Box 694, North Shields, NE27 9AF', value: 'North Tyneside Council (Recovery and Enforcement)' },
{ type: 'inss', address: 'Insolvency Department, 3 Graying Court, Doxford International Business Park, Sunderland, Tyne & Wear, SR3 3XG', value: 'Northern Rock Plc' },
{ type: 'inss', address: 'Selectapost 19, Rotherhan, South Yorkshire, S97 3DG', value: 'Northern Rock Plc (Personal Loans)' },
{ type: 'inss', address: 'Recovery Team, Revenues Section, Northumberland County Council, Wansbeck Square, Ashington, Northumberland, NE63 9XL', value: 'Northumberland County Council' },
{ type: 'inss', address: 'Northumbrian Water, Bankruptcy & Liquidation Team, P O Box 300, Durham, DH1 9WQ', value: 'Northumbrian Water Ltd' },
{ type: 'inss', address: 'Insolvency Department, PO Box 177, Cygnet Way, Houghton Le Spring, DH4 9AQ', value: 'Npower' },
{ type: 'inss', address: 'Insolvency Department, 3 Graying Court, Doxford International Business Park, Sunderland, Tyne & Wear, SR3 3XG', value: 'N-Ram' },
{ type: 'inss', address: 'SME Business Collections, Suite X-Y, Arlington Business Centre, Millshaw Park Lane, Leeds, LS11 0NE', value: 'O2 UK Ltd' },
{ type: 'inss', address: 'Civic Centre, PO Box 4, Debt Recovery, West Street, Oldham, OL1 1UH', value: 'Oldham Council' },
{ type: 'inss', address: 'Orange Insolvency Department, Senhouse Road, Darlington, DL1 4YB', value: 'Orange' },
{ type: 'inss', address: '3rd Floor, Westmead House, Farnborough, GU14 7LP', value: 'Osiris World Limited' },
{ type: 'inss', address: 'Griffin House, 40 Lever Street, Manchester, M60 6ES', value: 'Oxendales' },
{ type: 'inss', address: 'Oxford City Homes Rent Team, First Floor, 109-113 St Aldates, Oxford, OX1 1DS', value: 'Oxford City Council' },
{ type: 'inss', address: '5th Floor, Maitland House, Warrior Square, Southend-On-Sea, Essex, SS1 2JS', value: 'Pace Forward' },
{ type: 'inss', address: 'Pastdue Credit Solutions Ltd, Unit 1, Blair Court, Clydebank Business Park, Glasgow, G81 2LA', value: 'Pastdue Credit Solutions' },
{ type: 'inss', address: 'Collections and Recoveries, 2nd Floor, 12 Calthorpe Road, Edgebaston, Birmingham, B15 1FD', value: 'Payment Services Bureau (HSBC)' },
{ type: 'inss', address: '76 King Street, MANCHESTER, M2 4NH', value: 'Peachy Loans (Cash on the Go)' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Peter Craig' },
{ type: 'inss', address: 'PO Box 152, Darlington, Durham, DL3 9WT', value: 'Philips Collection Services Ltd' },
{ type: 'inss', address: '5th Floor, Maitland House, Warrior Square, Southend-On-Sea, Essex, SS1 2GX', value: 'Phoenix Recoveries (UK) Ltd SARL (Tessera)' },
{ type: 'inss', address: 'Plymouth City Council, Floor 5, Civic Centre, Armada Way, Plymouth, PL1 2AA', value: 'Plymouth City Council' },
{ type: 'inss', address: 'PO Box 8, West Street, Havant, Hampshire, PO9 1LG', value: 'Portsmouth Water Ltd' },
{ type: 'inss', address: 'PO Box 444, Bromley, BR1 1ZB', value: 'PRA Group (UK) Limited ' },
{ type: 'inss', address: 'Preston City Council, Legal Services, Lancaster Road, Preston, PR1 2RL', value: 'Preston City Council' },
{ type: 'inss', address: '1 Godwin Street, Bradford, BD1 2SU', value: 'Provident Financial Services Ltd' },
{ type: 'inss', address: '1 Godwin Street, Bradford, BD1 2SU', value: 'Provident Personal Credit' },
{ type: 'inss', address: '125 Chester Road, Sunderland, SR4 7HG', value: 'Ramsdens Financial Ltd' },
{ type: 'inss', address: 'c/o RSM Tenon, FAO Robert Beat, Salisbury House, 31 Finsbury Circus, London, EC2M 5SQ', value: 'RBS Plc' },
{ type: 'inss', address: 'Credit Management Services, PO Box 16337, 7 Brindley Place, Birmingham, B2 2YH', value: 'RBS Plc' },
{ type: 'inss', address: '1 Godwin Street, Bradford, BD1 2SU', value: 'Real Personal Credit' },
{ type: 'inss', address: 'Enterprise House, 1 Apex View, Leeds, LS11 9BH', value: 'Red Debt Collection Services' },
{ type: 'inss', address: 'International House, Kingsfield Court, Chester, Cheshire, CH4 9RF', value: 'Red2Black Collections Ltd' },
{ type: 'inss', address: 'Customer Service Department, Manchester, Lancashire, M99 2BS', value: 'Reliable Collections Ltd' },
{ type: 'inss', address: 'Capital Bank Leasing 9 Ltd, 7th Floor Oakland House, Talbot Road, Manchester, M16 0PQ', value: 'RENTSMART' },
{ type: 'inss', address: 'Carolina Way, Quays Reach, Salford, Greater Manchester, M50 2ZY', value: 'Robinson Way & Co Ltd' },
{ type: 'inss', address: 'Tessera Portfolio Management, 5th Floor, Maitland House, Southend-On-Sea, SS1 2JS', value: 'Rockwell Debt Collection Agency' },
{ type: 'inss', address: 'Wavell House, Rossendale, Lancashire, BB4 4NB', value: 'Rossendales Collections Limited' },
{ type: 'inss', address: 'Roxburghe House, Lavender Park Road, West Bayfleet, Surrey, KT14 6NA', value: 'Roxburghe (UK) Ltd' },
{ type: 'inss', address: 'The Woolwich Centre, 35 Wellington Street, LONDON, SE18 6HQ', value: 'Royal Borough of Greenwich' },
{ type: 'inss', address: '49 Huntbach Street, Hanley, Stoke-On-Trent, ST1 2BS', value: 'S & U Plc' },
{ type: 'inss', address: 'Suite One, 2nd Floor, Bellway House, 7 Worcester Road, Bromsgrove, Worcestershire, B61 7DL', value: 'S C Gray Solicitors Ltd' },
{ type: 'inss', address: 'PO Box 1173, Woking, Surrey, GU22 2BS', value: 'S.R.J Debt Recoveries' },
{ type: 'inss', address: 'Personal Insolvencies, Dundas House, PO Box 66, Rosyth, Fife, KY11 2YG', value: 'Sainsburys Bank plc' },
{ type: 'inss', address: 'Personal Insolvencies, Dundas House, PO Box 66, Rosyth, Fife, KY11 2YG', value: 'Sainsburys Bank plc' },
{ type: 'inss', address: 'Insolvency Team, Santander House, 201 Grafton Gate East, Milton Keynes, Buckinghamshire, MK9 1AN', value: 'Santander' },
{ type: 'inss', address: 'Recoveries Department, Capital House, 1 Bruntcliffe Way, Morley, Leeds, LS27 0JG', value: 'Santander Cards' },
{ type: 'inss', address: 'First Data, Janus House, JPT/G, Endeavour Drive, Basildon, Essex, SS14 3WF', value: 'SAV Credit Ltd' },
{ type: 'inss', address: 'Town Hall, St Nicholas Street, Scarborough, North Yorkshire, YO11 2HG', value: 'Scarborough Council' },
{ type: 'inss', address: 'Spectrum Building, 55 Blythswood Street, Glasgow, G2 7AT', value: 'ScotCall Debt Collecting Services' },
{ type: 'inss', address: 'Bankruptcy & Liquidation Department, 2nd Floor Grampian House, 200 Dunkeld Road, Perth, Perthshire, PH1 3GH', value: 'Scottish & Southern Energy' },
{ type: 'inss', address: 'Technical Services, Cathcart House, Spean Street, Glasgow, Lanarkshire, G44 4GE', value: 'Scottish Power Ltd' },
{ type: 'inss', address: 'c/o RSM Tenon, FAO Robert Beat, Salisbury House, 31 Finsbury Circus, London, EC2M 5SQ', value: 'Scottish Power Mastercard' },
{ type: 'inss', address: '49 Huntbach Street, Hanley, Stoke-On-Trent, ST1 2BS', value: 'SD Taylor' },
{ type: 'inss', address: 'Department SO, PO Box 499, 1-5 Queens Road Quadrant, Brighton, BN1 3XJ', value: 'Sechiari, Clarke & Mitchell' },
{ type: 'inss', address: 'St. Peters House, Balliol Road, Bootle. L20 3AB', value: 'Sefton MBC' },
{ type: 'inss', address: 'The Insolvency Department, Sherbourne House, St Martins Road, Coventry, CV3 6SD', value: 'Severn Trent Water Ltd' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Shop Direct Financial Services Ltd' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Shop Direct Home Shopping Ltd' },
{ type: 'inss', address: 'Central Collections Department, Kingston House, Centre 27 Business Park, Birstall, WF17 9TD', value: 'Shopacheck Financial Services Ltd' },
{ type: 'inss', address: '155 Bromford Lane, Erdington, Birmingham, B24 8DJ', value: 'Short Term Finance Ltd' },
{ type: 'inss', address: 'Griffin House, 40 Lever Street, Manchester, M60 6ES', value: 'Simply Be' },
{ type: 'inss', address: 'Barclaycard, Specialist Support Unit, PO Box 5402, Northampton, Northamptonshire, NN4 1ZR', value: 'Sky Card' },
{ type: 'inss', address: '7 Centaurs Business Centre, Grant Way, Isleworth, Middlesex, TW7 5QD', value: 'Sky Subscribers Services Ltd' },
{ type: 'inss', address: 'c/o Grant Thornton UK LLP, Hartwell House, 55-61 Victoria Street, Bristol, Avon, BS1 6FT', value: 'Smile' },
{ type: 'inss', address: 'South Cambridgeshire Hall, 6010 Cambourne Business Park, Cambourne, Cambridge, CB23 6EA', value: 'South Cambridgeshire District Council' },
{ type: 'inss', address: 'Rocfort Road, Snodland, Kent, ME6 5AH', value: 'South East Water' },
{ type: 'inss', address: 'Customer and Transactional Services, Council Offices, Castle Street, Thornbury, South Gloucestershire, BS35 1HF', value: 'South Gloucestershire Council' },
{ type: 'inss', address: 'The Council Office, St Peters Hill, Grantham, Lincs, NG31 6PZ', value: 'South Kesteven District Council' },
{ type: 'inss', address: 'Green Lane, Walsall, West Midlands, WS2 7PD', value: 'South Staffordshire Water plc' },
{ type: 'inss', address: 'Insolvency Team, PO Box 4762, Worthing, BN11 9NT', value: 'South West Water Ltd' },
{ type: 'inss', address: 'Tryst House, Glenbervie Business Park, Larbert, Stirling, FK5 4RB', value: 'Southern Counties Fuels' },
{ type: 'inss', address: 'Bankruptcy & Liquidation Department, Tom Johnson House, 3 Hunt Hill, Cumbernauld, Glasgow G68 9LF', value: 'Southern Electric' },
{ type: 'inss', address: 'Southern House, Yeoman Road, Worthing, West Sussex, BN13 3NX', value: 'Southern Water Services Ltd' },
{ type: 'inss', address: ' PO Box 728, Borehamwood, Herts, WD6 9GU', value: 'Speed-e-loans.com' },
{ type: 'inss', address: 'Anglia Revenues Partnership, Breckland House, St Nicholas Street, Thetford, Norfolk, IP24 1BT', value: 'St Edmundsbury Borough Council' },
{ type: 'inss', address: 'Civic Centre, Riverside, Stafford, ST16 3AQ', value: 'Stafford Borough Council' },
{ type: 'inss', address: 'PO Box 410, Billingham, Durham, TS23 2YD', value: 'Stockton on Tees Borough Council' },
{ type: 'inss', address: 'Council Offices, Ebley Mill, Stroud, Glos GL5 4UB', value: 'Stroud District Council' },
{ type: 'inss', address: '100 Bothwell Street, Glasgow, Lanarkshire, G2 7JD', value: 'Student Loans Company Ltd' },
{ type: 'inss', address: 'Express House, Clayton Business Park, Petre Road, Accrington, Lancashire, BB5 5JY', value: 'Studio Cards' },
{ type: 'inss', address: 'c/o RSM Tenon, FAO Robert Beat, Salisbury House, 31 Finsbury Circus, London, EC2M 5SQ', value: 'Style' },
{ type: 'inss', address: 'Melton Hill, Woodbridge, Suffolk, IP12 1AU', value: 'Suffolk Coastal District Council' },
{ type: 'inss', address: 'London Road, Redhill, Surrey, RH1 1LJ', value: 'Sutton & East Surrey Water Plc' },
{ type: 'inss', address: 'Bankruptcy & Liquidation Department, Tom Johnson House, 3 Hunt Hill, Cumbernauld, Glasgow G68 9LF ', value: 'Swalec' },
{ type: 'inss', address: 'Level 5 Plaza Commercial Centre,Bisazzi Street,Sliema,Malta,SLM 1640', value: 'Swift Sterling ' },
{ type: 'inss', address: '6-8 Great Marlborough Street, Manchester, M1 5SW', value: 'Swinton Group Ltd' },
{ type: 'inss', address: 'Chadwick House, Blenheim Court, Solihull, West Midlands, B91 2AA', value: 'Sygma Bank UK' },
{ type: 'inss', address: 'Benefits and Revenues, 88-90 Pier Avenue, CLACTON-ON-SEA, CO15 1TN', value: 'Tendring District Council' },
{ type: 'inss', address: 'Veolia Water East Ltd, Mill Hill, Mistley, Manningtree, Essex, CO11 2AZ', value: 'Tendring Hundred Water Services Ltd' },
{ type: 'inss', address: 'c/o RSM Tenon, FAO Robert Beat, Salisbury House, 31 Finsbury Circus, London, EC2M 5SQ', value: 'Tesco Personal Finance Plc' },
{ type: 'inss', address: 'Credit Management Services, PO Box 16337, 7 Brindley Place, Birmingham, B2 2YH', value: 'Tesco Personal Finance Plc' },
{ type: 'inss', address: '5th Floor, Maitland House, Warrior Square, Southend-On-Sea, Essex, SS1 2JS', value: 'Tessera Portfolio Management' },
{ type: 'inss', address: 'PO Box 286, Swindon, Wiltshire, SN38 2RA', value: 'Thames Water Utilities Ltd' },
{ type: 'inss', address: 'Ratho Park, Ratho Station, NEWBRIDGE, EH28 8QQ', value: 'The Cheque Centre' },
{ type: 'inss', address: 'Castlebridge Office Village, Kirtley Drive, Nottingham, NG7 1LD', value: 'The Money Shop' },
{ type: 'inss', address: 'PO Box 10081, Nottingham, NG2 9LX', value: 'The New Look Card' },
{ type: 'inss', address: 'Doxford Contact Centre, 6 Camberwell Way, Doxford Technology Park, Doxford, Sunderland, Tyne & Wear, SR3 3XN', value: 'T-Mobile (UK) Ltd' },
{ type: 'inss', address: 'Gibson Building, Gibson Drive, Kings Hill, West Malling, Kent, ME19 4LZ', value: 'Tonbridge & Malling Borough Council (Overpayments)' },
{ type: 'inss', address: 'A1 Pine Grange, Bath Road, Bournemouth, BH1 2PF', value: 'Tower Capital Limited' },
{ type: 'inss', address: '126-150 Washway Road, Sale, Manchester, M33 6AG', value: 'Trafford Housing Trust' },
{ type: 'inss', address: 'PO Box 183, Telford, Shropshire, TF2 2BU', value: 'Triton Credit Services' },
{ type: 'inss', address: 'The Clock Tower, Office No. 5, Chineham, Basingstoke, Hampshire, RG24 8BQ', value: 'Triumph Asset Service Ltd' },
{ type: 'inss', address: 'Collections Department, PO Box 2231, Gloucester, GL3 9EE', value: 'TSB Bank ' },
{ type: 'inss', address: 'PO Box 361, Ashford, TW15 9DZ', value: 'Txtloan' },
{ type: 'inss', address: 'c/o RSM Tenon, FAO Robert Beat, Salisbury House, 31 Finsbury Circus, London, EC2M 5SQ', value: 'Ulster Bank Ltd' },
{ type: 'inss', address: 'Ulster Bank  , Collections & Recoveries, Danesfort, Stranmillis Road, BELFAST, BT9 5UB', value: 'Ulster Bank Ltd' },
{ type: 'inss', address: 'Lingley Green Avenue, Lingley Mere Business Park, Great Sankey, Warrington, Lancashire, WA5 3LP', value: 'United Utilities plc' },
{ type: 'inss', address: 'Fifty Pembroke Court, Pembroke, Chatham Maritime, Catham, Kent, ME4 4EL', value: 'Vanquis Bank Ltd' },
{ type: 'inss', address: 'Mill Hill, Manningtree, Essex, CO11 2AZ', value: 'Veolia Water East Ltd' },
{ type: 'inss', address: 'The Cherry Garden, Cherry Garden Lane, Folkestone, Kent, CT19 4QB', value: 'Veolia Water Southeast Ltd' },
{ type: 'inss', address: 'Shop Direct Group, Sandringham House, Sandringham Avenue, Chelmsford, Essex, CM92 1LN', value: 'Very' },
{ type: 'inss', address: 'PO Box 800, Leeds, LS99 2AE', value: 'Viking Collection Services Ltd' },
{ type: 'inss', address: 'MBNA Customer Assistance PO Box 30, Chester Business Park, Wrexham Road, Chester, Cheshire, CH4 9FD', value: 'Virgin Credit Card' },
{ type: 'inss', address: 'Matrix Court, Siemens Way, Swansea Enterprise Park, Swansea, SA7 9BB', value: 'Virgin Media and Virgin Mobile' },
{ type: 'inss', address: 'Royal Avenue, Widnes, Cheshire, WA88 1AT', value: 'Virgin Money' },
{ type: 'inss', address: 'Pembroke House, Aynho Road, Adderbury, Banbury, Oxfordshire, OX17 3NS', value: 'Vodafone' },
{ type: 'inss', address: 'PO Box 10397, NOTTINGHAM, NG1 9JJ', value: 'Wage Day Advance' },
{ type: 'inss', address: 'Civic Centre, Ferrybridge Road, Castleford, WF10 4JH', value: 'Wakefield Metropolitan District Council' },
{ type: 'inss', address: 'PO Box 96, Lowestoft, Suffolk, NR32 1HW', value: 'Waveney District Council' },
{ type: 'inss', address: 'Mere Way, Ruddington Fields Business Park, Nottingham, NG11 6NZ', value: 'Welcome Finance Ltd' },
{ type: 'inss', address: 'PO Box 137, Hull, Yorkshire, HU2 8HF', value: 'Wescot Credit Services Ltd' },
{ type: 'inss', address: '1 Clevedon Walk, Nailsea, Bristol, Avon, BS48 1WA', value: 'Wessex Water Services Ltd' },
{ type: 'inss', address: 'Accounts Receivable and HB Overpayments Manager, Wirral Council, Municipal Building, Cleveland Street, Birkenhead, Wirral, CH41 6BU', value: 'Wirral Council (Housing Benefit Overpayment)' },
{ type: 'inss', address: 'Legal Services, Civic Centre, St. Peters Square, Wolverhampton, WV1 1RL', value: 'Wolverhampton City Council' },
{ type: 'inss', address: 'Benefits Overpayments Team, PO Box 3300, Wolverhampton, WV1 1ZT', value: 'Wolverhampton City Council- Housing Benefit' },
{ type: 'inss', address: 'PO Box 250, Wolverhamption, WV2 1AX', value: 'Wolverhampton City Council- Local Taxes Division' },
{ type: 'inss', address: 'Rents Management, Unit Hickman Avenue, wolverhampton, WV1 2BY', value: 'Wolverhampton Homes' },
{ type: 'inss', address: 'Wonga.com. Hardship Team, Sheffield, S95 1AR', value: 'Wonga' },
{ type: 'inss', address: 'Legal Notice Unit, PO Box 4313, Manchester, M61 0AR', value: 'Woolwich' },
{ type: 'inss', address: 'County Hall, Spetchley Road, Worcestershire, WR5 2NP', value: 'Worcestershire County Council' },
{ type: 'inss', address: 'Debt Relief Orders, Collections, PO Box 764. Bruswick Point, Wade Lane, Leeds, LS11 9JJ', value: 'Yorkshire Bank' },
{ type: 'inss', address: 'Debt Relief Orders, Collections, PO Box 764. Bruswick Point, Wade Lane, Leeds, LS11 9JJ', value: 'Yorkshire Bank' },
{ type: 'inss', address: 'Brook House, 4 Gladstone Road, Scarborough, YO12 7BH', value: 'Yorkshire Coast Homes' },
{ type: 'inss', address: 'Recovery Department, PO Box 52, Bradford, BD3 7YD', value: 'Yorkshire Water Services Ltd' },
{ type: 'inss', address: 'YHN House, Benton Park Road, Newcastle Upon Tyne, Tyne and Wear, NE7 7LX', value: 'Your Homes Newcastle' }
];
 
    
    // constructs the suggestion engine
var creditors = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  local: creditors
});
 
// kicks off the loading/processing of `local` and `prefetch`
creditors.initialize();
 
	$('#creditors.typeahead').typeahead({
	  hint: true,
	  highlight: true,
	  minLength: 1
	},
	{
	  name: 'creditors',
	  displayKey: 'value',
	  // `ttAdapter` wraps the suggestion engine in an adapter that
	  // is compatible with the typeahead jQuery plugin
	  source: creditors.ttAdapter(),
	  templates: {
	        suggestion: function (stock) {
	            return '<div class="row"><div class="col-sm-5">' + stock.value + '</div>' + '<div class="col-sm-7 choose-address">' + stock.address + '</div></div>';
	        }
	    }
	});

});